import { MenuItem } from '../types';

export const DEFAULT_MENU_ITEMS: Record<string, MenuItem> = {
  // Minuman Kopi & Non-Kopi
  'menu-1': {
    id: 'menu-1',
    name: 'Kopi Susu Gula Aren',
    category: 'Minuman',
    price: 18000,
    description: 'Espresso blend pilihan, susu segar creamy, dan pemanis gula aren alami.',
    image: '☕',
    isAvailable: true,
    isBestSeller: true,
    optionGroups: [
      {
        title: 'Suhu',
        type: 'single',
        options: [{ name: 'Dingin (Ice)' }, { name: 'Panas (Hot)' }],
      },
      {
        title: 'Level Gula',
        type: 'single',
        options: [{ name: 'Normal' }, { name: 'Less Sugar' }, { name: 'Tanpa Gula' }],
      },
      {
        title: 'Topping Tambahan',
        type: 'multiple',
        options: [
          { name: 'Extra Shot Espresso', extraPrice: 5000 },
          { name: 'Krim Macchiato', extraPrice: 4000 },
        ],
      },
    ],
  },
  'menu-2': {
    id: 'menu-2',
    name: 'Americano / Long Black',
    category: 'Minuman',
    price: 15000,
    description: 'Espresso ganda diseduh dengan air panas atau dingin segar.',
    image: '☕',
    isAvailable: true,
    optionGroups: [
      {
        title: 'Suhu',
        type: 'single',
        options: [{ name: 'Dingin (Ice)' }, { name: 'Panas (Hot)' }],
      },
      {
        title: 'Pemanis',
        type: 'single',
        options: [{ name: 'Tanpa Gula' }, { name: 'Gula Cair Normal' }],
      },
    ],
  },
  'menu-3': {
    id: 'menu-3',
    name: 'Caramel Macchiato',
    category: 'Minuman',
    price: 22000,
    description: 'Kopi susu dengan sirup vanila dan lapisan saus karamel lezat.',
    image: '☕',
    isAvailable: true,
    isBestSeller: true,
    optionGroups: [
      {
        title: 'Suhu',
        type: 'single',
        options: [{ name: 'Dingin (Ice)' }, { name: 'Panas (Hot)' }],
      },
    ],
  },
  'menu-4': {
    id: 'menu-4',
    name: 'Matcha Latte Ice',
    category: 'Minuman',
    price: 20000,
    description: 'Bubuk matcha murni berpadu dengan susu segar dingin.',
    image: '🍵',
    isAvailable: true,
    optionGroups: [
      {
        title: 'Level Gula',
        type: 'single',
        options: [{ name: 'Normal' }, { name: 'Less Sugar' }],
      },
    ],
  },
  'menu-5': {
    id: 'menu-5',
    name: 'Es Teh Manis Jasmine',
    category: 'Minuman',
    price: 6000,
    description: 'Teh melati wangi diseduh dingin menyegarkan tenggorokan setelah bernyanyi.',
    image: '🧋',
    isAvailable: true,
  },
  'menu-6': {
    id: 'menu-6',
    name: 'Lemon Tea Segar',
    category: 'Minuman',
    price: 12000,
    description: 'Seduhan teh segar dengan perasan lemon asli dan es batu melimpah.',
    image: '🍋',
    isAvailable: true,
    isPromo: true,
  },

  // Makanan Utama
  'menu-7': {
    id: 'menu-7',
    name: 'Nasi Goreng Spesial Kafe',
    category: 'Makanan',
    price: 25000,
    description: 'Nasi goreng harum bumbu rempah dengan suwiran ayam, sosis, dan kerupuk.',
    image: '🍛',
    isAvailable: true,
    isBestSeller: true,
    optionGroups: [
      {
        title: 'Level Pedas',
        type: 'single',
        options: [{ name: 'Tidak Pedas' }, { name: 'Sedang' }, { name: 'Ekstra Pedas' }],
      },
      {
        title: 'Tambahan',
        type: 'multiple',
        options: [
          { name: 'Telur Ceplok / Dadar', extraPrice: 4000 },
          { name: 'Sosis Ekstra', extraPrice: 4000 },
        ],
      },
    ],
  },
  'menu-8': {
    id: 'menu-8',
    name: 'Mie Nyemek Telur Pedas',
    category: 'Makanan',
    price: 18000,
    description: 'Mie goreng kuah kental gurih dengan orak-arik telur, sayur sawi, dan cabai rawit.',
    image: '🍜',
    isAvailable: true,
    optionGroups: [
      {
        title: 'Level Pedas',
        type: 'single',
        options: [{ name: 'Sedang' }, { name: 'Pedas Nampol' }],
      },
    ],
  },
  'menu-9': {
    id: 'menu-9',
    name: 'Ayam Geprek Sambal Bawang + Nasi',
    category: 'Makanan',
    price: 23000,
    description: 'Ayam krispi renyah digeprek dengan sambal bawang pedas gurih khas nusantara.',
    image: '🍗',
    isAvailable: true,
  },
  'menu-10': {
    id: 'menu-10',
    name: 'Rice Bowl Daging Sapi Teriyaki',
    category: 'Makanan',
    price: 28000,
    description: 'Irisan daging sapi empuk saus teriyaki manis gurih di atas nasi hangat.',
    image: '🥩',
    isAvailable: true,
  },

  // Camilan / Snack
  'menu-11': {
    id: 'menu-11',
    name: 'Kentang Goreng Keju (French Fries)',
    category: 'Snack',
    price: 15000,
    description: 'Kentang stik renyah gurih ditaburi bumbu keju cheddar lezat.',
    image: '🍟',
    isAvailable: true,
    isBestSeller: true,
    optionGroups: [
      {
        title: 'Pilihan Bumbu',
        type: 'single',
        options: [{ name: 'Keju Asin' }, { name: 'Barbeque' }, { name: 'Balado Pedas' }],
      },
    ],
  },
  'menu-12': {
    id: 'menu-12',
    name: 'Cireng Krispi Bumbu Rujak',
    category: 'Snack',
    price: 14000,
    description: 'Cireng kenyal renyah isi 8 pcs disajikan dengan cocolan saus rujak pedas manis.',
    image: '🥟',
    isAvailable: true,
  },
  'menu-13': {
    id: 'menu-13',
    name: 'Pisang Goreng Cokelat Keju',
    category: 'Snack',
    price: 16000,
    description: 'Pisang kepok manis digoreng krispi dengan limpahan susu kental, cokelat, dan parutan keju.',
    image: '🍌',
    isAvailable: true,
    isPromo: true,
  },
  'menu-14': {
    id: 'menu-14',
    name: 'Roti Bakar Kaya Butter',
    category: 'Snack',
    price: 16000,
    description: 'Roti bakar empuk isi selai srikaya harum dan lelehan mentega premium.',
    image: '🍞',
    isAvailable: true,
  },

  // Paket Karaoke Combo & Sewa Ruang
  'menu-15': {
    id: 'menu-15',
    name: 'Paket Nongkrong 4 Orang',
    category: 'Paket',
    price: 65000,
    description: 'Paket hemat: 1 Porsi Kentang Goreng + 1 Cireng Rujak + 4 Es Teh Manis.',
    image: '🍱',
    isAvailable: true,
    isBestSeller: true,
  },
  'menu-16': {
    id: 'menu-16',
    name: 'Sewa Room Karaoke 1 Jam (Reguler)',
    category: 'Paket',
    price: 50000,
    description: 'Sewa ruang karaoke 1 jam penuh dengan sound system profesional dan layar TV ganda.',
    image: '🎤',
    isAvailable: true,
    isBestSeller: true,
  },
  'menu-17': {
    id: 'menu-17',
    name: 'Paket Karaoke 2 Jam + Snack & Pitcher Tea',
    category: 'Paket',
    price: 125000,
    description: 'Sewa karaoke 2 jam + 1 French Fries Keju + 1 Pitcher Teh Manis Dingin untuk 4 orang.',
    image: '🎉',
    isAvailable: true,
    isPromo: true,
  },
  'menu-18': {
    id: 'menu-18',
    name: 'Voucher Ekstra Karaoke (5 Lagu)',
    category: 'Paket',
    price: 20000,
    description: 'Tambahan kuota 5 lagu bebas pilih untuk request lagu di antrean karaoke meja.',
    image: '🎟️',
    isAvailable: true,
  },
};
