import { MenuItem } from '../types';

export const DEFAULT_MENU_ITEMS: Record<string, MenuItem> = {
  // Minuman Kopi & Non-Kopi
  'menu-1': {
    id: 'menu-1',
    name: 'Kopi Susu Gula Aren',
    category: 'Minuman',
    price: 18000,
    description: 'Espresso blend pilihan, susu segar creamy, dan pemanis gula aren alami.',
    image: '☕',
    isAvailable: true,
  },
  'menu-2': {
    id: 'menu-2',
    name: 'Americano / Long Black',
    category: 'Minuman',
    price: 15000,
    description: 'Espresso ganda diseduh dengan air panas atau dingin segar.',
    image: '☕',
    isAvailable: true,
  },
  'menu-3': {
    id: 'menu-3',
    name: 'Caramel Macchiato',
    category: 'Minuman',
    price: 22000,
    description: 'Kopi susu dengan sirup vanila dan lapisan saus karamel lezat.',
    image: '☕',
    isAvailable: true,
  },
  'menu-4': {
    id: 'menu-4',
    name: 'Matcha Latte Ice',
    category: 'Minuman',
    price: 20000,
    description: 'Bubuk matcha murni berpadu dengan susu segar dingin.',
    image: '🍵',
    isAvailable: true,
  },
  'menu-5': {
    id: 'menu-5',
    name: 'Es Teh Manis Jasmine',
    category: 'Minuman',
    price: 6000,
    description: 'Teh melati wangi diseduh dingin menyegarkan tenggorokan setelah bernyanyi.',
    image: '🧋',
    isAvailable: true,
  },
  'menu-6': {
    id: 'menu-6',
    name: 'Lemon Tea Ice',
    category: 'Minuman',
    price: 12000,
    description: 'Teh segar dipadu perasan sari lemon asli.',
    image: '🍋',
    isAvailable: true,
  },
  'menu-7': {
    id: 'menu-7',
    name: 'Air Mineral Prima 600ml',
    category: 'Minuman',
    price: 5000,
    description: 'Air mineral dingin atau suhu ruangan.',
    image: '🍶',
    isAvailable: true,
  },

  // Makanan Utama
  'menu-8': {
    id: 'menu-8',
    name: 'Nasi Goreng Spesial Kafe',
    category: 'Makanan',
    price: 25000,
    description: 'Nasi goreng bumbu racik khas dengan suwiran ayam, sosis, telur mata sapi, dan kerupuk.',
    image: '🍛',
    isAvailable: true,
  },
  'menu-9': {
    id: 'menu-9',
    name: 'Mie Goreng Jawa Nyemek',
    category: 'Makanan',
    price: 22000,
    description: 'Mie telur kuah kental gurih dengan sayuran segar, telur, dan irisan bakso.',
    image: '🍜',
    isAvailable: true,
  },
  'menu-10': {
    id: 'menu-10',
    name: 'Ayam Geprek Sambal Bawang + Nasi',
    category: 'Makanan',
    price: 24000,
    description: 'Ayam krispi renyah digeprek dengan cabai rawit pedas mantap plus nasi putih.',
    image: '🍗',
    isAvailable: true,
  },
  'menu-11': {
    id: 'menu-11',
    name: 'Rice Bowl Chicken Teriyaki',
    category: 'Makanan',
    price: 26000,
    description: 'Nasi pulen hangat dengan potongan ayam saus teriyaki manis gurih dan taburan wijen.',
    image: '🍚',
    isAvailable: true,
  },

  // Snack & Camilan
  'menu-12': {
    id: 'menu-12',
    name: 'French Fries Crispy',
    category: 'Snack',
    price: 15000,
    description: 'Kentang goreng renyah bumbu gurih disajikan dengan saus tomat dan cabai.',
    image: '🍟',
    isAvailable: true,
  },
  'menu-13': {
    id: 'menu-13',
    name: 'Cireng Krispi Bumbu Rujak',
    category: 'Snack',
    price: 14000,
    description: 'Cireng kenyal garing di luar dengan cocolan saus gula merah pedas manis gurih.',
    image: '🥟',
    isAvailable: true,
  },
  'menu-14': {
    id: 'menu-14',
    name: 'Pisang Bakar Cokelat Keju',
    category: 'Snack',
    price: 16000,
    description: 'Pisang kepok manis dipanggang empuk dengan taburan keju parut dan krimer cokelat.',
    image: '🍌',
    isAvailable: true,
  },
  'menu-15': {
    id: 'menu-15',
    name: 'Karaoke Combo Platter (Best Seller)',
    category: 'Paket',
    price: 35000,
    description: 'Porsi besar cocok untuk rame-rame: Kombinasi sosis panggang, nugget ayam, dan kentang goreng crispy.',
    image: '🍱',
    isAvailable: true,
  },
};
